language:
  php

php:
  - nightly
  - 7.3
  - 7.2.1
  - 7.2
  - 7.1.13
  - 7.1
  - 7.0.27
  - 7.0
  - 5.6.33
  - 5.6
  - 5.5.38
  - 5.5
  - 5.4.45
  - 5.4

env:
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1

matrix:
  allow_failures:
    - php: 7.3
    - php: nightly

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;

notifications:
  email: false


