language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
  - 5.1
  - 5.0
  - 4.4
  - 4.3
  - 4.2
  - 4.1
  - 4.0
  - 3.0

matrix:
  allow_failures:
    - php: 7.1

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;

notifications:
  email: false
