language: php
php:
  - 7.1.5
  - 7.1
  - 7.0.19
  - 7.0
  - 5.6.30
  - 5.6
  - 5.5.38
  - 5.5
  - 5.4.45
  - 5.4
  - 5.3.29
  - 5.3
  - 5.2.17
  - 5.2

matrix:
  allow_failures:
    - php: 7.0

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;

notifications:
  email: false
