title: WP Missed Schedule Fix WP Failed Future Posts
description: Find missed schedule posts and it republish them correctly. Checking every 5 minutes all posts that match the problem, and fixed 5 items per session.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
